# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XPMQ4kxJz4dp5FsMJlVGEgX4TWXHTix6

**Task 07: Querying RDF(s)**
"""

# !pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

from validation import Report

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
# Do not change the name of the variables
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.parse(github_storage+"/rdf/data06.ttl", format="TTL")
report = Report()

"""**TASK 7.1a: For all classes, list each classURI. If the class belogs to another class, then list its superclass.**
**Do the exercise in RDFLib returning a list of Tuples: (class, superclass) called "result". If a class does not have a super class, then return None as the superclass**
"""

# TO DO
result = []  # list of tuples
for cls in g.subjects(RDF.type, RDFS.Class):
    superclass = None
    for sup in g.objects(cls, RDFS.subClassOf):
        superclass = sup
        break
    result.append((cls, superclass))

# Visualize the results
for r in result:
  print(r)

## Validation: Do not remove
report.validate_07_1a(result)

"""**TASK 7.1b: Repeat the same exercise in SPARQL, returning the variables ?c (class) and ?sc (superclass)**"""

query =  '''
SELECT ?c ?sc
WHERE {
  ?c a rdfs:Class .
  OPTIONAL { ?c rdfs:subClassOf ?sc . }
}
'''

for r in g.query(query):
  print(r.c, r.sc)

## Validation: Do not remove
report.validate_07_1b(query,g)

"""**TASK 7.2a: List all individuals of "Person" with RDFLib (remember the subClasses). Return the individual URIs in a list called "individuals"**

"""

ns = Namespace("http://oeg.fi.upm.es/def/people#")

# variable to return
individuals = []

# Función recursiva para obtener todas las subclases
def subclasses_of(base_class):
    found = set()
    for sub in g.subjects(RDFS.subClassOf, base_class):
        found.add(sub)
        found |= subclasses_of(sub)
    return found

# Obtener Person y todas sus subclases
all_classes = {ns.Person} | subclasses_of(ns.Person)

# Buscar individuos que sean instancia de esas clases
for cls in all_classes:
    for subj in g.subjects(RDF.type, cls):
        individuals.append(subj)

# visualize results
for i in individuals:
  print(i)

# validation. Do not remove
report.validate_07_02a(individuals)

"""**TASK 7.2b: Repeat the same exercise in SPARQL, returning the individual URIs in a variable ?ind**"""

query = '''

PREFIX : <http://oeg.fi.upm.es/def/people#>

SELECT DISTINCT ?ind
WHERE {
  ?ind a ?cls .
  ?cls rdfs:subClassOf* :Person .
}
'''

# Visualize the results
for r in g.query(query):
  print(r.ind)

## Validation: Do not remove
report.validate_07_02b(g, query)

"""**TASK 7.3:  List the name and type of those who know Rocky (in SPARQL only). Use name and type as variables in the query**"""

#TO DO

query =  '''

PREFIX : <http://oeg.fi.upm.es/def/people#>

SELECT ?name ?type
WHERE {
  ?person :knows :Rocky .
  ?person a ?type .
  ?person rdfs:label ?name .
}
'''

# Visualize the results
for r in g.query(query):
  print(r.name, r.type)

## Validation: Do not remove
report.validate_07_03(g, query)

"""**Task 7.4: List the name of those entities who have a colleague with a dog, or that have a collegue who has a colleague who has a dog (in SPARQL). Return the results in a variable called name**"""

# TO DO

query =  '''

PREFIX : <http://oeg.fi.upm.es/def/people#>

SELECT DISTINCT ?name
WHERE {
  {
    ?person :hasColleague ?col .
    ?col :ownsPet ?pet .
    ?pet a :Animal .
    ?person rdfs:label ?name .
  }
  UNION
  {
    ?person :hasColleague ?col1 .
    ?col1 :hasColleague ?col2 .
    ?col2 :ownsPet ?pet2 .
    ?pet2 a :Animal .
    ?person rdfs:label ?name .
  }
}
'''

# Visualize the results

for r in g.query(query):
  print(r.name)

## Validation: Do not remove
report.validate_07_04(g,query)
report.save_report("_Task_07")