# -*- coding: utf-8 -*-
"""Task08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m6nQvdNwaWZgyLGJbi5YzYnDD-_w6cSN

**Task 08: Completing missing data**
"""

# !pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"/rdf/data01.rdf", format="xml")
g2.parse(github_storage+"/rdf/data02.rdf", format="xml")

"""Tarea: lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas."""

from rdflib import RDF

# Namespaces
EX = Namespace("http://data.org#")
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

# Obtenemos todas las personas del primer grafo
persons_g1 = [s for s in g1.subjects(RDF.type, EX.Person)]

# Función auxiliar para obtener un valor o None
def get_value(graph, subject, predicate):
    vals = list(graph.objects(subject, predicate))
    return vals[0] if vals else None

# Mostrar datos iniciales
for person in persons_g1:
    print(f"Persona: {person}")
    print(f"Given: {get_value(g1, person, VCARD.Given)}")
    print(f"Family: {get_value(g1, person, VCARD.Family)}")
    print(f"Email: {get_value(g1, person, VCARD.EMAIL)}")
    print("-"*40)

# Completar valores faltantes desde g2
for person in persons_g1:
    for prop in [VCARD.Given, VCARD.Family, VCARD.EMAIL]:
        if not list(g1.objects(person, prop)):
            for val in g2.objects(person, prop):
                g1.add((person, prop, val))

# Mostrar resultados finales
for person in persons_g1:
    print(f"Persona: {person}")
    print(f"Given: {get_value(g1, person, VCARD.Given)}")
    print(f"Family: {get_value(g1, person, VCARD.Family)}")
    print(f"Email: {get_value(g1, person, VCARD.EMAIL)}")
    print("="*40)