# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EWJTNfNaRrw8RSFkfFRDk9rA-luWh-ft

**Task 06: Modifying RDF(s)**
"""

# !pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

"""Import RDFLib main methods"""

from rdflib import Graph, Namespace, Literal, XSD
from rdflib.namespace import RDF, RDFS
from validation import Report
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
r = Report()

"""Create a new class named Researcher"""

ns = Namespace("http://mydomain.org#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**Task 6.0: Create new prefixes for "ontology" and "person" as shown in slide 14 of the Slidedeck 01a.RDF(s)-SPARQL shown in class.**"""

# this task is validated in the next step

# Definición de nuevos prefijos para la ontología y las personas
ont = Namespace("http://oeg.fi.upm.es/def/people#")
prs = Namespace("http://oeg.fi.upm.es/resource/person/")

# Asociamos los prefijos al grafo RDF
g.namespace_manager.bind("ont", ont, override=False)
g.namespace_manager.bind("prs", prs, override=False)

"""**TASK 6.1: Reproduce the taxonomy of classes shown in slide 34 in class (all the classes under "Vocabulario", Slidedeck: 01a.RDF(s)-SPARQL). Add labels for each of them as they are in the diagram (exactly) with no language tags. Remember adding the correct datatype (xsd:String) when appropriate**

"""

# TO DO

# Definición de las clases del vocabulario y sus etiquetas
clases = {
    "Person": None,
    "Professor": "Person",
    "FullProfessor": "Professor",
    "AssociateProfessor": "Professor",
    "InterimAssociateProfessor": "AssociateProfessor"
}

# Añadimos las clases y sus relaciones jerárquicas al grafo
for clase, superclase in clases.items():
    clase_uri = ont[clase]
    g.add((clase_uri, RDF.type, RDFS.Class))
    g.add((clase_uri, RDFS.label, Literal(clase, datatype=XSD.string)))
    if superclase:
        g.add((clase_uri, RDFS.subClassOf, ont[superclase]))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_01(g)

"""**TASK 6.2: Add the 3 properties shown in slide 36. Add labels for each of them (exactly as they are in the slide, with no language tags), and their corresponding domains and ranges using RDFS. Remember adding the correct datatype (xsd:String) when appropriate. If a property has no range, make it a literal (string)**"""

# TO DO

propiedades = {
    "hasColleague": {
        "dominio": ont.Person,
        "rango": ont.Person
    },
    "hasHomePage": {
        "dominio": ont.FullProfessor,
        "rango": RDFS.Literal
    },
    "hasName": {
        "dominio": ont.Person,
        "rango": RDFS.Literal
    }
}

# Añadimos cada propiedad con su etiqueta, dominio y rango
for nombre, info in propiedades.items():
    prop = ont[nombre]
    g.add((prop, RDF.type, RDF.Property))
    g.add((prop, RDFS.label, Literal(nombre, datatype=XSD.string)))
    g.add((prop, RDFS.domain, info["dominio"]))
    g.add((prop, RDFS.range, info["rango"]))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_02(g)

"""**TASK 6.3: Create the individuals shown in slide 36 under "Datos". Link them with the same relationships shown in the diagram."**"""

# TO DO

# Definición de los individuos y sus clases
individuos = {
    "Raul": ont.InterimAssociateProfessor,
    "Asun": ont.FullProfessor,
    "Oscar": ont.AssociateProfessor
}

# Crear instancias y añadir etiquetas
for nombre, clase in individuos.items():
    uri = prs[nombre]
    g.add((uri, RDF.type, clase))
    g.add((uri, RDFS.label, Literal(nombre, datatype=XSD.string)))

# Añadir relaciones según el diagrama
g.add((prs.Raul, ont.hasColleague, prs.Asun))
g.add((prs.Asun, ont.hasColleague, prs.Raul))
g.add((prs.Oscar, ont.hasColleague, prs.Asun))
g.add((prs.Asun, ont.hasHomePage, Literal("http://www.oeg-upm.net/", datatype=XSD.string)))
g.add((prs.Oscar, ont.hasName, Literal("Oscar", datatype=XSD.string)))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

r.validate_task_06_03(g)

"""**TASK 6.4: Add to the individual person:Oscar the email address, given and family names. Use the properties already included in example 4 to describe Jane and John (https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials/rdf/example4.rdf). Do not import the namespaces, add them manually**

"""

# TO DO

# Definimos manualmente los namespaces usados en example4.rdf
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")
foaf = Namespace("http://xmlns.com/foaf/0.1/")

# Enlazamos los prefijos al grafo
g.namespace_manager.bind("vcard", vcard, override=False)
g.namespace_manager.bind("foaf", foaf, override=False)

# Email (propiedad de FOAF)
g.add((prs.Oscar, foaf.email, Literal("oRodriguezh@somewhere.com", datatype=XSD.string)))

# Nombre de pila (propiedad VCARD.Given)
g.add((prs.Oscar, vcard.Given, Literal("Oscar", datatype=XSD.string)))

# Apellido (propiedad VCARD.Family)
g.add((prs.Oscar, vcard.Family, Literal("Rodriguez", datatype=XSD.string)))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_04(g)
r.save_report("_Task_06")